const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sb=window.jasaSupabase;
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const statusLabel={searching:'Mencari mitra',accepted:'Mitra menerima',on_the_way:'Mitra menuju lokasi',arrived:'Mitra tiba',quoting:'Pemeriksaan & penawaran',awaiting_approval:'Menunggu persetujuan',working:'Sedang dikerjakan',completed:'Pekerjaan selesai',paid:'Sudah dibayar',rated:'Selesai & diberi rating',cancelled:'Dibatalkan'};
async function session(){const {data}=await sb.auth.getSession();if(!data.session){location.href='login.html';return null}return data.session}
async function profile(){const s=await session();if(!s)return null;const {data,error}=await sb.from('profiles').select('*').eq('id',s.user.id).single();if(error){alert(error.message);return null}return data}
async function logout(){await sb.auth.signOut();location.href='login.html'}
function bindLogout(){$('#logout')?.addEventListener('click',logout)}
function flash(t){const e=$('#flash');if(e){e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2500)}}
async function guardRole(role){const p=await profile();if(!p)return null;if(p.role!==role){location.href='index.html';return null}return p}
async function uploadImages(files,userId){const urls=[];for(const f of [...files].slice(0,5)){if(f.size>6291456)throw new Error('Foto maksimal 6MB');const path=userId+'/'+crypto.randomUUID()+'-'+f.name.replace(/[^a-zA-Z0-9._-]/g,'_');const {error}=await sb.storage.from('order-media').upload(path,f,{contentType:f.type,upsert:false});if(error)throw error;urls.push(sb.storage.from('order-media').getPublicUrl(path).data.publicUrl)}return urls}
async function initCustomer(){
 const p=await guardRole('customer');if(!p)return;bindLogout();$('#name').textContent=p.full_name||'Pelanggan';
 let services=[],addresses=[],orders=[];
 async function load(){const a=await sb.from('services').select('*').eq('is_active',true).order('sort_order');services=a.data||[];const b=await sb.from('addresses').select('*').eq('customer_id',p.id).order('is_default',{ascending:false});addresses=b.data||[];const c=await sb.from('orders').select('*,services(name),quotes(id,total_amount,status,note,created_at)').eq('customer_id',p.id).order('created_at',{ascending:false});orders=c.data||[];render()}
 function render(){ $('#services').innerHTML=services.length?services.map(x=>`<button class="service" data-id="${x.id}"><b>${esc(x.name)}</b><span>${esc(x.description||'Pesan layanan')}</span></button>`).join(''):'<div class="empty">Belum ada layanan aktif.</div>';$('#addresses').innerHTML=addresses.length?addresses.map(x=>`<option value="${x.id}">${esc(x.label||'Alamat')} — ${esc(x.address_text)}</option>`).join(''):'<option value="">Tambahkan alamat dulu</option>';$('#orders').innerHTML=orders.map(o=>`<article class="order"><div><b>${esc(o.services?.name||'Jasa')}</b><span class="pill">${statusLabel[o.status]||o.status}</span></div><p>${esc(o.description||'')}</p><small>${new Date(o.created_at).toLocaleString('id-ID')}</small><div class="actions">${o.status==='awaiting_approval'&&o.quotes?.[0]?'<button data-act="approve" data-id="'+o.quotes[0].id+'">Setujui '+money(o.quotes[0].total_amount)+'</button>':''}${o.status==='awaiting_approval'&&o.quotes?.[0]?'<button class="secondary" data-act="reject" data-id="'+o.quotes[0].id+'">Tolak penawaran</button>':''}${['searching','accepted','on_the_way','arrived','quoting'].includes(o.status)?'<button class="secondary" data-act="cancel" data-id="'+o.id+'">Batalkan</button>':''}${o.status==='completed'?'<button data-act="cash" data-id="'+o.id+'">Bayar Cash</button>':''}${o.status==='paid'?'<button data-act="review" data-id="'+o.id+'">Beri Rating</button>':''}</div></article>`).join('')||'<div class="empty">Belum ada pesanan.</div>'}
 $('#services').onclick=e=>{const b=e.target.closest('.service');if(b){$('#serviceId').value=b.dataset.id;document.querySelector('#orderForm').scrollIntoView({behavior:'smooth'})}};
 $('#addAddress').onclick=async()=>{const text=prompt('Alamat lengkap:');if(!text)return;const label=prompt('Label, mis. Rumah:')||'Alamat';const {error}=await sb.from('addresses').insert({customer_id:p.id,label,address_text:text});if(error)alert(error.message);else load()};
 $('#orderForm').onsubmit=async e=>{e.preventDefault();try{const urls=await uploadImages($('#photos').files,p.id);const {error}=await sb.from('orders').insert({customer_id:p.id,service_id:$('#serviceId').value,address_id:$('#addresses').value||null,description:$('#description').value,photo_urls:urls});if(error)throw error;flash('Pesanan dibuat');e.target.reset();await load()}catch(x){alert(x.message)}};
 $('#orders').onclick=async e=>{const b=e.target.closest('button[data-act]');if(!b)return;try{let r;if(b.dataset.act==='approve')r=await sb.rpc('customer_approve_quote',{p_quote:b.dataset.id});if(b.dataset.act==='reject')r=await sb.rpc('customer_reject_quote',{p_quote:b.dataset.id});if(b.dataset.act==='cash')r=await sb.rpc('mark_cash_payment',{p_order:b.dataset.id});if(b.dataset.act==='online'){const method=prompt('Metode pembayaran: qris atau bank_transfer','qris');if(!method)return;r=await sb.rpc('create_payment',{p_order:b.dataset.id,p_method:method})}if(b.dataset.act==='cancel')r=await sb.rpc('customer_cancel_order',{p_order:b.dataset.id,p_reason:'Dibatalkan pelanggan'});if(b.dataset.act==='review'){const rating=Number(prompt('Rating 1-5:'));if(!rating)return;const review=prompt('Ulasan (opsional):')||'';r=await sb.rpc('submit_review',{p_order:b.dataset.id,p_rating:rating,p_review:review})}if(r?.error)throw r.error;await load()}catch(x){alert(x.message)}};
 await load();setInterval(load,10000);
}
async function initMitra(){
 const p=await guardRole('mitra');if(!p)return;bindLogout();$('#name').textContent=p.full_name||'Mitra';let mp=(await sb.from('mitra_profiles').select('*').eq('id',p.id).single()).data;
 async function load(){mp=(await sb.from('mitra_profiles').select('*').eq('id',p.id).single()).data;const [sv,ms,ord,w]=await Promise.all([sb.from('services').select('*').eq('is_active',true).order('sort_order'),sb.from('mitra_services').select('service_id').eq('mitra_id',p.id),sb.from('orders').select('*,services(name),quotes(*)').or('mitra_id.eq.'+p.id+',status.eq.searching').order('created_at',{ascending:false}),sb.from('wallets').select('*').eq('mitra_id',p.id).maybeSingle()]);render(sv.data||[],ms.data||[],ord.data||[],w.data)}
 function render(sv,ms,orders,w){$('#verify').textContent=mp.verification_status;$('#online').checked=mp.online;$('#rating').textContent=(mp.rating_avg||0)+' ('+(mp.rating_count||0)+')';$('#balance').textContent=money(w?.balance);$('#services').innerHTML=sv.map(x=>`<label class="check"><input type="checkbox" value="${x.id}" ${ms.some(m=>m.service_id===x.id)?'checked':''}> ${esc(x.name)}</label>`).join('');$('#orders').innerHTML=orders.map(o=>`<article class="order"><div><b>${esc(o.services?.name||'Jasa')}</b><span class="pill">${statusLabel[o.status]||o.status}</span></div><p>${esc(o.description||'')}</p><small>${new Date(o.created_at).toLocaleString('id-ID')}</small><div class="actions">${o.status==='searching'?'<button data-a="accept" data-id="'+o.id+'">Terima Order</button>':''}${o.mitra_id===p.id&&o.status==='accepted'?'<button data-a="status" data-s="on_the_way" data-id="'+o.id+'">Mulai Jalan</button>':''}${o.mitra_id===p.id&&o.status==='on_the_way'?'<button data-a="status" data-s="arrived" data-id="'+o.id+'">Sudah Tiba</button>':''}${o.mitra_id===p.id&&['arrived','quoting'].includes(o.status)?'<button data-a="quote" data-id="'+o.id+'">Buat Penawaran</button>':''}${o.mitra_id===p.id&&o.status==='working'?'<button data-a="status" data-s="completed" data-id="'+o.id+'">Tandai Selesai</button>':''}</div></article>`).join('')||'<div class="empty">Belum ada order.</div>'}
 $('#online').onchange=async()=>{const {error}=await sb.from('mitra_profiles').update({online:$('#online').checked}).eq('id',p.id);if(error){alert(error.message);$('#online').checked=!$('#online').checked}else load()};
 $('#saveServices').onclick=async()=>{await sb.from('mitra_services').delete().eq('mitra_id',p.id);const ids=$$('#services input:checked').map(x=>x.value);if(ids.length)await sb.from('mitra_services').insert(ids.map(service_id=>({mitra_id:p.id,service_id})));flash('Layanan mitra disimpan');load()};
 $('#orders').onclick=async e=>{const b=e.target.closest('button[data-a]');if(!b)return;try{let r;if(b.dataset.a==='accept')r=await sb.rpc('mitra_accept_order',{p_order:b.dataset.id});if(b.dataset.a==='status')r=await sb.rpc('mitra_set_order_status',{p_order:b.dataset.id,p_status:b.dataset.s,p_note:null});if(b.dataset.a==='quote'){const a=Number(prompt('Biaya jasa:', '0')||0),m=Number(prompt('Material:', '0')||0),t=Number(prompt('Transport:', '0')||0),o=Number(prompt('Lainnya:', '0')||0),n=prompt('Catatan penawaran:')||'';r=await sb.rpc('submit_quote',{p_order:b.dataset.id,p_service:a,p_material:m,p_transport:t,p_other:o,p_note:n})}if(r?.error)throw r.error;load()}catch(x){alert(x.message)}};
 $('#payoutForm').onsubmit=async e=>{e.preventDefault();const amount=Number($('#payoutAmount').value);const {data:w}=await sb.from('wallets').select('balance').eq('mitra_id',p.id).maybeSingle();if(!w||amount<=0||amount>w.balance)return alert('Saldo tidak mencukupi');const r=await sb.rpc('request_payout',{p_amount:amount,p_bank:$('#bank').value,p_account:$('#account').value,p_name:$('#accountName').value});if(r.error)alert(r.error.message);else{flash('Permintaan payout dikirim');e.target.reset();load()}};
 await load();setInterval(load,10000);
}
async function initAdmin(){
 const p=await guardRole('admin');if(!p)return;bindLogout();
 async function load(){const [users,mitra,orders,services,settings,payments]=await Promise.all([sb.from('profiles').select('*').order('created_at',{ascending:false}),sb.from('mitra_profiles').select('*,profiles(full_name,phone)').order('created_at',{ascending:false}),sb.from('orders').select('*,services(name)').order('created_at',{ascending:false}),sb.from('services').select('*').order('sort_order'),sb.from('app_settings').select('*'),sb.from('payments').select('*,orders(order_number)').order('created_at',{ascending:false})]);$('#users').innerHTML=(users.data||[]).map(u=>`<tr><td>${esc(u.full_name||'-')}</td><td>${esc(u.phone||'-')}</td><td><span class="pill">${u.role}</span></td><td>${u.is_active?'Aktif':'Nonaktif'}</td></tr>`).join('');$('#mitra').innerHTML=(mitra.data||[]).map(m=>`<tr><td>${esc(m.profiles?.full_name||'-')}</td><td>${m.online?'Online':'Offline'}</td><td>${m.verification_status}</td><td>${m.rating_avg}</td><td><button data-v="${m.id}" data-s="verified">Verifikasi</button><button class="secondary" data-v="${m.id}" data-s="rejected">Tolak</button></td></tr>`).join('');$('#orders').innerHTML=(orders.data||[]).map(o=>`<tr><td>${o.order_number}</td><td>${esc(o.services?.name||'-')}</td><td>${o.status}</td><td>${money(o.total_customer)}</td></tr>`).join('');$('#services').innerHTML=(services.data||[]).map(s=>`<tr><td>${esc(s.name)}</td><td>${s.is_active?'Aktif':'Nonaktif'}</td><td><button data-del="${s.id}">Hapus</button></td></tr>`).join('');$('#payments').innerHTML=(payments.data||[]).map(x=>`<tr><td>${esc(x.orders?.order_number||'-')}</td><td>${x.method}</td><td>${x.status}</td><td>${money(x.amount)}</td><td>${x.status==='pending'?'<button data-pay="'+x.order_id+'">Tandai dibayar</button>':''}</td></tr>`).join('')||'<tr><td colspan="5">Belum ada pembayaran</td></tr>';$('#settings').innerHTML=(settings.data||[]).map(s=>`<label>${esc(s.key)}<input data-key="${esc(s.key)}" value="${esc(JSON.stringify(s.value))}"></label>`).join('')||'<p class="muted">Belum ada pengaturan.</p>'}
 $('#addService').onsubmit=async e=>{e.preventDefault();const {error}=await sb.from('services').insert({name:$('#svcName').value,slug:$('#svcName').value.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-'),description:$('#svcDesc').value,sort_order:Number($('#svcSort').value||0)});if(error)alert(error.message);else{e.target.reset();load()}};
 $('#mitra').onclick=async e=>{const b=e.target.closest('button[data-v]');if(!b)return;const {error}=await sb.from('mitra_profiles').update({verification_status:b.dataset.s}).eq('id',b.dataset.v);if(error)alert(error.message);else load()};
 $('#payments').onclick=async e=>{const b=e.target.closest('button[data-pay]');if(!b)return;const r=await sb.rpc('admin_mark_payment_paid',{p_order:b.dataset.pay});if(r.error)alert(r.error.message);else load()};$('#services').onclick=async e=>{const b=e.target.closest('button[data-del]');if(!b)return;if(confirm('Hapus layanan ini?')){const {error}=await sb.from('services').delete().eq('id',b.dataset.del);if(error)alert(error.message);else load()}};
 $('#saveSettings').onclick=async()=>{for(const i of $$('#settings input[data-key]')){let v;try{v=JSON.parse(i.value)}catch{v=i.value}await sb.from('app_settings').upsert({key:i.dataset.key,value:v,updated_by:p.id})}flash('Pengaturan disimpan');load()};
 $('#addSetting').onclick=async()=>{const k=prompt('Key pengaturan:');if(!k)return;await sb.from('app_settings').insert({key:k,value:{}});load()};
 await load();
}
document.addEventListener('DOMContentLoaded',()=>{const role=document.body.dataset.role;if(role==='customer')initCustomer();if(role==='mitra')initMitra();if(role==='admin')initAdmin()});